// protoc -I=./src/main/proto --csharp_out=C:/Development/workspace/unity3d/Cosmic-Scavengers-Unity-Client/Assets/Scripts/CosmicScavengers/Protobuf/WorldData/ world_data.proto

syntax = "proto3";

option java_package = "com.cosmicscavengers.networking.protobuf.worlddata";
option csharp_namespace = "CosmicScavengers.Networking.Protobuf.WorldData";

// --- World Data Structures for Serialization ---

// Mirrors the World JPA entity for network transmission.
message WorldData {
  // Database primary key ID
  int64 id = 1;

  // Raw JSON payload containing the world configuration.
  string config_json = 2;
}